CREATE TABLE alquileres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_bicicleta VARCHAR(50) NOT NULL,
    nombre_cliente VARCHAR(150) NOT NULL,
    fecha_hora_inicio TIMESTAMP NOT NULL,
    duracion_estimada_horas INTEGER NOT NULL CHECK (duracion_estimada_horas > 0),
    tarifa_por_hora BIGINT NOT NULL CHECK (tarifa_por_hora > 0),
    estado VARCHAR(20) NOT NULL,
    fecha_hora_devolucion TIMESTAMP,
    horas_facturables INTEGER,
    costo_base BIGINT,
    multa BIGINT,
    total BIGINT
);